### ISSUE TITLE
more a hint than an issue (directory structure)

### ISSUE THREAD

**Issue by TimoGo** [ogarcia/docker-taskd#4]
Thank you for your great Dockerfile!

The configuration is straightforward, but I didnt found any hint how to generating the client certificate and where to put these files.

The following commands did the the job for me, but maybe there is an more easy way.

after RUNning the container, enter it with:
 docker run -ti --rm   -v /srv/taskd:/var/taskd   myown/taskd /bin/sh

 cd /var/taskd/pki
 ./generate.client timo 2>timo.out
 
 cd ..
 cd orgs
 mkdir myown
 cd myown
 mkdir groups
 mkdir users
 chmod 700 users
 cd users
 mkdir timo
 cd timo
 echo "user=timo" >config
 chmod 700 config 
 
 exit (leaving the container)

After that:
copy ca.cert.pem client.cert.pem client.key.pem  to the client ( path  ~/.task/ )

Ive added the following paragraph in the .taskrc
 taskd.certificate=/root/.task/client.cert.pem
 taskd.key=/root/.task/client.key.pem
 taskd.ca=/root/.task/ca.cert.pem
 taskd.server=localhost:53589
 taskd.credentials=myown/timo/timo

**Comment by ogarcia** [comment]
Hi @TimoGo 

In **Manual Setup** section of [README.md](https://github.com/ogarcia/docker-taskd/blob/master/README.md#manual-setup) you can read that I make mention to [Taskwarrior Docs](https://taskwarrior.org/docs/). If you go to these docs you can find [Taskserver Setup Guide](https://gitpitch.com/GothenburgBitFactory/taskserver-setup#/) that says exactly the info that you posted in your issue [here](https://gitpitch.com/GothenburgBitFactory/taskserver-setup#/9/3) and [here](https://gitpitch.com/GothenburgBitFactory/taskserver-setup#/13/3).

I don't add this info to my Readme because would duplicate the work and may be outdated.
